name: SimpleLifeSteal
version: '${project.version}'
main: com.simplelifesteal.SimpleLifeSteal
api-version: 1.19
authors: [ the5gi ]
description: A simple Life Steal plugin that doesn't require a config! Add it to your server and instantly have it working :)

commands:
  simplelifesteal:
    description: thingy command
    usage: /simplelifesteal
    permission: sls.sls
  resethearts:
    description: resets a players hearts
    usage: /resethearts player
    permission: sls.admin
  sethearts:
    description: sets a players hearts
    usage: /sethearts player amount
    permission: sls.admin
  giveheartitem:
    description: gives a player the heart item
    usage: /giveheartitem player amount
    permission: sls.admin
